image: ${DOCKER_REGISTRY}hseeberger/scala-sbt:17.0.2_1.6.2_2.13.8

.sbt_cache:
  variables:
    COURSIER_CACHE: sbt_cache/coursier
  cache:
    key: "$CI_BUILD_REF_NAME-$CI_JOB_NAME"
    paths:
      - "sbt_cache/coursier"

.sbt_artifacts_reports:
  artifacts:
    reports:
      junit:
        - "**/target/test-reports/TEST*.xml"

test:
  extends:
    - .sbt_cache
    - .sbt_artifacts_reports
  script:
    - sbt test
  only:
    - merge_requests
